name: CI Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21 (Zulu OpenJDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  
          java-version: '21'

      - name: Grant permission for Gradle wrapper
        run: chmod +x ./demo/gradlew

      - name: Build with Gradle
        run: ./demo/gradlew build --no-daemon

      - name: Run tests
        run: ./demo/gradlew test --no-daemon

      - name: Run coverage tests
        run: ./demo/gradlew jacocoTestReport

      - name: Upload test coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./demo/build/reports/jacoco/test/html
