name: CI Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21 (Zulu OpenJDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  
          java-version: '21'

      - name: Grant permission for Gradle wrapper
        run: cd demo && chmod +x ./gradlew

      - name: Build with Gradle
        run: cd demo && ./gradlew bootJar --no-daemon

      - name: Run tests
        run:  cd demo && ./gradlew test --no-daemon

      - name: Run coverage tests
        if: github.ref == 'refs/heads/master'
        run: cd demo && ./gradlew check

      - name: Upload test coverage report
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./demo/build/reports/jacoco/test/html
